[package]
name = "juego_piezas_playa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.4.0"
nohash-hasher = "0.2.0"
pathfinding = "3.0.13"
